# Config file reference can be found at https://embarkstudios.github.io/cargo-deny/checks/cfg.html.

[graph]
all-features        = true
exclude-dev         = true
no-default-features = true

[advisories]
yanked = "deny"

[bans]
allow-wildcard-paths = false
multiple-versions    = "allow"

[licenses]
allow                  = ["Apache-2.0", "BSL-1.0", "MIT", "Unicode-3.0", "Zlib"]
private                = { ignore = false }
unused-allowed-license = "deny"

[[licenses.clarify]]
expression    = "MIT AND ISC AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
name          = "ring"

[sources]
unknown-git      = "deny"
unknown-registry = "deny"
