repos:
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        entry: cargo +nightly-2026-05-22 fmt
      - id: clippy
  - repo: https://github.com/EmbarkStudios/cargo-deny
    rev: 0.20.2
    hooks:
      - id: cargo-deny
        args:
          - --locked
          - --config
          - .cargo-deny.toml
          - check
          - --hide-inclusion-graph
          - --show-stats
          - -D
          - warnings
        env:
          CARGO_BUILD_WARNINGS: deny
  - repo: https://github.com/ComPWA/taplo-pre-commit
    rev: v0.9.3
    hooks:
      - id: taplo-format
      - id: taplo-lint
