exclude = ["target/**"]

[formatting]
align_entries         = true
allowed_blank_lines   = 1
column_width          = 120
keys                  = ["build-dependencies", "dependencies", "dev-dependencies"]
reorder_arrays        = true
reorder_inline_tables = true
reorder_keys          = true
