name: Update Cargo cache

inputs:
  key:
    description: The key to use for the cache
    required: true

description: Update the Cargo artifacts cache at the provided key

runs:
  using: composite
  steps:
    - name: Set up Cargo cache
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # Version 4.2.3
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # Must be in sync with the key used in the setup-cargo-cache action
        key: ${{ inputs.key }}->#${{ github.run_id }}
      continue-on-error: true
