name: Setup Cargo cache

inputs:
  key:
    description: The key to use for the cache
    required: true
  github-token:
    description: Valid GitHub token to interact with GitHub REST API
    required: true

description: Set up cache read operations for Cargo artifacts

runs:
  using: composite
  steps:
    - name: Set up Cargo cache
      uses: actions/cache/restore@v4
      with:
        path: |
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        # Must be in sync with the key used in the update-cargo-cache action
        key: ${{ inputs.key }}->#${{ github.run_id }}
        restore-keys: |
          ${{ inputs.key }}
      continue-on-error: true
    - name: Delete retrieved cache
      uses: ./.github/actions/prune-cache
      with:
        key-prefix: ${{ inputs.key }}->#
        github-token: ${{ inputs.github-token }}
      continue-on-error: true
