[package]
name = "ping_pong"
version = "0.1.0"
edition = "2021"

[dependencies]
overwatch-rs = { path = "../../overwatch-rs" }
overwatch-derive = { path = "../../overwatch-derive" }
async-trait = "0.1.83"
tokio = { version = "1", features = ["macros"] }
