[package]
name = "ping_pong"
version = "0.1.0"
edition = "2021"

[dependencies]
overwatch = { path = "../../overwatch" }
overwatch-derive = { path = "../../overwatch-derive" }
async-trait = "0.1.83"
tokio = { version = "1.42.0", features = ["macros"] }
thiserror = "2.0.8"
serde_json = "1.0.134"
serde = { version = "1.0.216", features = ["derive"] }
const_format = "0.2.34"
project-root = "0.2.2"
tracing = "0.1.41"
