on:
  push:
    tags:
      - v*.*.*

name: Release

jobs:
  release:
    steps:
      - uses: actions/checkout@v4
      - uses: katyo/publish-crates@v1
        with:
          registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
